apiVersion: v1
kind: Service
metadata:
  name: authz_server
spec:
  ports:
    - port: 8081 #指定Service所需的虚拟端口号为8081
      targetPort: 8090 #使用targetPort指定后端Pod的端口号
  selector:
    app: authz #指定后端Pod拥有的label: app=authz
